name: test-and-lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
        # make depends on uv
      - name: Install dependencies
        run: |
          pip install uv
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Run test coverage
        run: |
          make test-coverage
      - name: SonarQubeScan
        uses: docs/example-action@b16d2601a6b948e2fb26f3772276581f31daa7cd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Den-R3R5_python-project-50
            -Dsonar.organization=den-r3r5
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=gendiff